#!/bin/bash
# Vendor the SHARED rules engine into this repo.
#
# Althar's Keep (../benchmarks/godot) is the canonical home of the rules.
# This project does not fork them — it takes a byte-identical generated
# copy, and records a SHA-256 manifest so drift is DETECTED rather than
# trusted. `tools/test.sh` runs `--check` first, so a tower change cannot
# be reported done while the rules are out of sync.
#
#   tools/sync-rules.sh          regenerate sim/ from the source
#   tools/sync-rules.sh --check  verify sim/ matches the source; exit 1 on drift
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="../benchmarks/godot/sim"
DST="sim"
MANIFEST="$DST/MANIFEST"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

if [ ! -d "$SRC" ]; then
	echo "sync-rules: source not found: $SRC" >&2
	echo "  Althar's Keep must be checked out beside this project." >&2
	exit 1
fi

tmp_manifest="$(mktemp)"
{
	echo "# GENERATED by tools/sync-rules.sh — do not edit files in this directory."
	echo "# Canonical source: Althar's Keep  benchmarks/godot/sim/"
	echo "# Every file below is byte-identical to its source. Editing a copy here"
	echo "# makes tools/sync-rules.sh --check fail, which tools/test.sh enforces."
} > "$tmp_manifest"
drift=0

for f in "$SRC"/*.gd "$SRC"/*.gd.uid; do
	[ -e "$f" ] || continue
	base="$(basename "$f")"
	if [ "$CHECK" = "1" ]; then
		if [ ! -f "$DST/$base" ] || ! cmp -s "$f" "$DST/$base"; then
			echo "DRIFT  sim/$base differs from $SRC/$base"
			drift=1
		fi
	else
		cp -f "$f" "$DST/$base"
	fi
	shasum -a 256 "$f" | awk -v b="$base" '{print $1"  "b}' >> "$tmp_manifest"
done

if [ "$CHECK" = "1" ]; then
	if ! cmp -s "$tmp_manifest" "$MANIFEST"; then
		echo "DRIFT  sim/MANIFEST is stale"
		drift=1
	fi
	rm -f "$tmp_manifest"
	if [ "$drift" = "1" ]; then
		echo
		echo "The shared rules have changed in Althar's Keep."
		echo "Run: tools/sync-rules.sh   (then re-run tools/test.sh)"
		exit 1
	fi
	echo "rules in sync with Althar's Keep ($(grep -cv '^#' "$MANIFEST") files)"
	exit 0
fi

mv "$tmp_manifest" "$MANIFEST"
echo "synced $(grep -cv '^#' "$MANIFEST") files from $SRC"
